@startuml

' definitions
' -----------
hide circle
hide empty methods
hide empty attributes

usecase r as "Recenser les \n demandes de stage"
usecase d as "Déclarer une \n demande de stage"

actor Responsable
actor Entreprise 

r -[hidden]-> d

Responsable -> r
Entreprise -> d

@enduml
