source 'https://rubygems.org'

group :development, :test do
  gem 'asciidoctor'
  gem 'asciidoctor-diagram'
  gem 'pygments.rb'
  gem 'guard'
  gem 'guard-shell'
  gem 'guard-livereload'
  gem 'rspec'
  gem 'rspec-expectations'
  gem 'link-checker'
  gem 'tilt'
  gem 'haml'
  gem 'thread_safe'
  gem 'slim'
  gem 'concurrent-ruby'
end
