source 'https://rubygems.org'

group :development, :test do
  gem 'asciidoctor'
  gem 'asciidoctor-diagram'
  gem 'pygments.rb'
  # gem 'guard'
  # gem 'guard-shell'
  # gem 'guard-livereload'
  # gem 'rspec'
  # gem 'rspec-expectations'
  # gem 'link-checker'
  gem 'thread_safe'
  gem 'concurrent-ruby'  
  gem 'asciidoctor-revealjs' 
  gem 'haml'
  gem 'tilt', '~>2.0'
  gem 'slim', '~>4.0'
end
